### ISSUE TITLE
samples-js-chat/README.adoc

### ISSUE THREAD

**Issue by marcellanz** [cloudstateio/samples-js-chat#15]
@tringuyen-yw as you've asked in chat. 
I add it here for convenience as the PR is already merged. I'm not native English, so double-check my comments regarding wording. I hope that helps.

- which are part of Lightbend Cloudstate **Cloudstate** Chat Sample => which are part of Lightbend ~~Cloudstate~~ Cloudstate Chat Sample
- For the Image shown, I'd not cross Wording like the arrow to users; it's just a distracting, especially if you took the time to draw it nicely with shadows (sorry to be that pedantic).
- Javascript => JavaScript
- GRPC => gRPC
- Friends is a stateful servic**e u**sing an Observed-Removed Set ORSet CRDT to store/retrieve the list of friends of **a** user.
- your services store/retrieve state without requiring => your services store **and** retrieve state without requiring
- Presence is a stateful servic**e u**sing a Vote CRDT to store/retrieve the online status of **a** user.
- In this repo => In this repo**sitory**
- Check with docker version, version v19.03+ recommended => Check with `docker version`**. Version v19.03+ is recommended.**

- This is at deployment time**,** when all the services collaborate together that we can really appreciate the true benefits of microservices. And in particular their stateful and serverless abilities. => It is at deployment time when all the services collaborate together that we can really appreciate the true benefits of a **serverless** deployment model. In particular **in terms of** their stateful and serverless abilities.

- In general, also with the last PR, we talk about microservices, I think I read nearly nothing about microservices in Cloudstate land. I think they are, but they are also not. I don't know what the intended wording is from LB but it should be consistent.
- Mac OS X is called just **macOS** these days. It's inconsistent named too: "MacOS", "Mac OSX"

**Comment by tringuyen-yw** [comment]
Fixed in PR #19
