### ISSUE TITLE
samples-js-chat/friends/README.adoc

### ISSUE THREAD

**Issue by marcellanz** [cloudstateio/samples-js-chat#16]
@tringuyen-yw as you've asked in chat :)

- has no UI => has no User Interface. I'd start with the full wording the first time you use the abbreviation. It gives the text a nice flow, I think.
- Javascript => JavaScript
- The user "Albert" has 2 friends (Niels and Paul) => The user "Albert" has 2 friends**, Niels and Paul.**
- The diagram below shows the chat application is architected as 3 microservices, deployed in a Kubernetes cluster. => The diagram below shows **that** the chat application is architected as 3 microservices **and** deployed **on a** Kubernetes cluster. 
- The application flow is explained in Cloudstate Chat Sample. => The application flow is explained in **the** Cloudstate Chat Sample.
- In this section, we focus only on the design of the Friends service as stateful serverless using Cloudstate => In this section, we focus only on the design of the Friends service as stateful serverless using Cloudstate. **<<< end with a dot.**
- The Friends service is stateful, ie. the state of the user entity is fully preserved. => The Friends service is stateful **where** the state of the user entity is fully preserved.
- If the user entity went out of scope in the Chat UI (eg. user disconnected or closed the browser). When the user connects back again, the Chat UI invokes the Friends service to retrieve the state (ie. the FriendsList). => these are two sentences where the first starts with "When..." but does not **what when**.
- GRPC => gRPC
- messages is annotated as "entity key".  => messages is annotated as **an** "entity key".
- Now we create the code **and** open a file called index.js. First, **we add** some setup code:
- the value will bne defaulted to => the value will **be** defaulted to
- Now we define some command handlers => Next, we define some command handlers <<< I'd alternate with "Now" and "Next" and possibly other continuous binding words to give a flow, like you do with "Finally" following that.
- ...

TODO: section 4. and 5.

**Comment by tringuyen-yw** [comment]
Thanks a lot @marcellanz for the thorough review. All fixed.

**Comment by tringuyen-yw** [comment]
Fixed in PR #19
