### ISSUE TITLE
When applying "presence" service, pods never report "ready"

### ISSUE THREAD

**Issue by michaelpnash** [cloudstateio/samples-js-chat#3]
When running 
`kubectl apply -f https://raw.githubusercontent.com/cloudstateio/samples-js-chat/master/deploy/presence.yaml`
One or more pods never report "ready", but there is no obvious error.

This is when running in:

minikube start --cpus 4 --memory 8192 --kubernetes-version=1.15.6

This might be a documentation issue - e.g. it could be better explanation of how to diagnose/troubleshoot the problem, but currently at least a couple of people trying it have been stalled at this point.

**Comment by tringuyen-yw** [comment]
This issue (filed in Dec 2019) is no longer relevant since June 2020, when the open source Chat Sample has been replaced by the "Lightbend Cloudstate" version.
